export const GET_TRANSLATION = "GET_TRANSLATION";
export const UPDATE_TRANSLATION_ERRORS = "UPDATE_TRANSLATION_ERRORS";
export const RESET_LANGUAGE_ERROR = "RESET_LANGUAGE_ERROR";
export const RESET_TRANSLATION_ERROR = "RESET_TRANSLATION_ERROR";
export const UPDATE_LYRICS_ERROR = "UPDATE_LYRICS_ERROR";
export const GET_LYRICS = "GET_LYRICS";
export const RESET_LYRICS_ERROR = "RESET_LYRICS_ERROR";
export const UPDATE_SEARCH_ERROR = "UPDATE_SEARCH_ERROR";
export const GET_RESULTS = "GET_RESULTS";
export const RESET_SEARCH_ERROR = "RESET_SEARCH_ERROR";
export const GET_ALBUMS = "GET_ALBUMS";
export const GET_TRACKS = "GET_TRACKS";

