export const GET_TRANSLATION = "GET_TRANSLATION";
export const UPDATE_ERRORS = "UPDATE_ERRORS";
export const RESET_LANGUAGE_ERROR = "RESET_LANGUAGE_ERROR";
export const RESET_TRANSLATION_ERROR = "RESET_TRANSLATION_ERROR";